import Foundation
import PackagePlugin

@main
struct TobiasConfigPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        // Read pubspec.yaml
        let pubspecPath = context.package.directory.appending("../pubspec.yaml")
        
        guard let pubspecData = try? Data(contentsOf: URL(fileURLWithPath: pubspecPath.string)),
              let pubspecString = String(data: pubspecData, encoding: .utf8) else {
            Diagnostics.error("Could not read pubspec.yaml")
            return []
        }
        
        // Parse YAML (simplified - for production, use a proper YAML parser)
        let useNoUtdid = pubspecString.contains("no_utdid: true")
        
        Diagnostics.remark("Using SDK variant: \(useNoUtdid ? "NoUtdid" : "Standard")")
        
        // Generate configuration file
        let configFile = context.pluginWorkDirectory.appending("TobiasConfig.swift")
        let configContent = """
        // Auto-generated by TobiasConfigPlugin
        enum TobiasConfig {
            static let useNoUtdid = \(useNoUtdid)
        }
        """
        
        try configContent.write(to: URL(fileURLWithPath: configFile.string), atomically: true, encoding: .utf8)
        
        return []
    }
}

